### ISSUE TITLE
ReactLoadable.flushRequires does not exist and { js, styles } contains <spans>

### ISSUE THREAD

**Issue by mnpenner** [faceyspacey/webpack-flush-chunks#2]
This appears to be wrong/outdated:

```js
const moduleIds = ReactLoadable.flushRequires()
```

AFAICT, that's been replaced by either [`flushServerSideRequirePaths` or `flushwebpackRequireWeakIds`](https://github.com/thejameskyle/react-loadable#flushserversiderequirepaths--flushwebpackrequireweakids), not sure which.

Secondly, these guys:

```js
const { js, styles } = flushChunks(moduleIds, stats)
```

Wrap the output in spans. For example, I'm getting:

```html
  <span id='__styles__'>
          <link rel='stylesheet' href='http://localhost:8041/main.css' />
        </span>
  <span id='__javascript__'>
          <script type='text/javascript' src='http://localhost:8041/bootstrap.no_css.js'></script>
<script type='text/javascript' src='http://localhost:8041/bundle.no_css.js'></script>
        </span>
```

I don't think these spans are necessary considering they're not React components, are they?

Also, `rootDir` appears to be required, even with webpack.

**Comment by faceyspacey** [comment]
- rootDir isn't required with webpack. Run the boilerplate instead of implementing it from scratch. Your server is likely still thinking the code is in node land because you marked it as an external. The boilerplate removes it from externals.

- the spans are there so strings are consistent with React components. React 16 will remove the need for this.

- the boilerplate makes use of the old methods. flushRequires is in fact new. It's part of a pending PR to react-loadable. This repo is kind of a secret to whoever finds it. It's not released yet, but you should definitely give it a try as it's in very solid shape and I'm just waiting for final decisions to be made within the RL repo.

Anyway start with the boilerplate and then once you get it working, strip out the code you don't need while making sure it still works and then move that code to your app. Let me know how that goes.

**Comment by mnpenner** [comment]
1. Aha. You are quite right -- I had marked it as external.
2. Is it necessary to remain consistent with React components? It can't be mounted anyway if we do it this way.
3. [This PR](https://github.com/thejameskyle/react-loadable/pull/37)? I think I'll wait for it to be merged, then give it a go :smile: 

I'm actually using Koa instead of Express, so I can't use the webpack dev middleware. I know there's one for Koa too, but I didn't work well when I tried it. Thus I've decided it's best to keep my HTTP server and WDS completely separate. I do it this way for PHP too and it works great.

**Comment by faceyspacey** [comment]
2. what do you mean it can't be mounted?
3. yes this one

...i'd really try Express. It's more than just webpack dev middleware. It's  webpack-hot-middleware and webpack-hot-server-middleware, which is a powerful combination since it makes your code on both the client and server powered by HMR. If only your client is updating, you will get checksum mismatches where what's rendered on the server won't match what's rendered on the client as the client responds to changes.

**Comment by mnpenner** [comment]
> what do you mean it can't be mounted?

These strings:

```
const { js, styles } = flushChunks(moduleIds, stats)
```

Are not React components. When you do sever-side rendering, the client script won't detect those and manage them for you. They don't have `data-reactids`. Thus there's no benefit to conforming with React syntax. There's no need to wrap them in spans. It needlessly prevents me from putting my CSS in the `<head>` like I want.

> i'd really try Express. 

I still get all the benefits you're talking about without using the middleware. There's no need to bundle it into my app. Server-side HMR is a little trickier but you can do it with `webpack/hot/poll`. If you integrate it right, you can hot-reload anything, not just React components. I do get the checksum mismatch warnings.

**Comment by faceyspacey** [comment]
I feel you. It originally was like that. Perhaps I'll put them back to not having container spans. As I recall you can still put them in the head, and you only get a warning. That might be fine for you for now. You can also get the raw filenames and do it yourself, which is probably best for you for now.

`const { scripts, stylesheets } = flushChunks(moduleIds, stats)`

...Also, generally, you don't want these elements to have `data-reactids`, or your bundle on the client will re-render them. I keep all such stuff outside of `<div id="root" dangerouslySetInnerHTML={{ __html: app }} />`.

The main idea was in case you wrote code to find the container selector by id. Then if you switched to strings, that selector wouldn't also be there. Originally, this was important because of CSS HMR where I'd actually remove the css in the container element once the JS loaded, at which point `style-loader` within the JS would handle HMR. But in the end I managed to get CSS HMR to work for both the js from `style-loader` and the static sheets.

**Comment by faceyspacey** [comment]
```js
const app = ReactDOM.renderToString(<App />)
const moduleIds = flushRequires()
const { scripts, stylesheets, publicPath } = flushChunks(moduleIds, stats)

res.send(`
  <!doctype html>
  <html>
    <head>
      <title>Hello World</title>
      ${stylesheets.map(name =>
        `<link rel="stylesheet" href="${publicPath}/${name}"></script>`
      ).join('\n')}
    </head>
    <body>
      <div id="root">${app}</div>

      ${scripts.map(name =>
        `<script src="/assets/${name}"></script>`
      ).join('\n')}
    </body>
  </html>
`)
```

**Comment by faceyspacey** [comment]
fyi, i removed the wrapper spans for the strings as per your request.

**Comment by mnpenner** [comment]
Awesome. Thank you very much.
