### ISSUE TITLE
Using with renderToNodeStream

### ISSUE THREAD

**Issue by davidfurlong** [faceyspacey/webpack-flush-chunks#41]
Is there a way to use this with `renderToNodeStream` from react 16?
It seems we need to flush chunks after SSR, but we also need to inject styles into `head`. So not possible?

**Comment by faceyspacey** [comment]
yea, that's a yet-to-be-solved problem in all of the React game. The only solution is looking like we're gonna have to push things back to the route level, which is the plan for Redux-First Router. I.e. code-splitting coupled to your routing tools. 

For now, you're just gonna have to make a hash of routes to chunk names and manually serve the correct chunks (their css + js) based on the route. 

I'm gonna close this as I have things in the works for this as part of the Rudy rollout. 

ps. styled-components et al are currently grappling with this as well. Most of these packages don't even want to deal with this, as it means a major refactoring, and it's unclear if it's even going to work glitch-free to send style tags at the end of each component. It will work technically, but while streaming, my guess is it might look glitchy on first load on the client, especially on slower connections. If that turns out to be the case, then static *route-level-disocvered* sheets will be the *only* solution for real, which is unfortunate since those new css components are otherwise the "right" way for react. That said, you'll still be able to use those components, just not with *render-time* css. They'll have to make a version of their packages geared towards a more static approach, similar to *extractStatic* in `emotion`.
