### ISSUE TITLE
Webpack 4

### ISSUE THREAD

**Issue by chrischandler25** [faceyspacey/webpack-flush-chunks#58]
I'm pretty new to React, and event more so to webpack.  I wanted to use your demo as bootstrap code for an application that I'm working, but hoped I could upgrade to Webpack 4.
Once I did that, I received a number of errors around the use of CommonsChunkPlugin, which it seems no longer exists.  It didn't look to me like the recommended migration would work, and the little bits of info I found on google seemed to agree.

Do you have these components working with Webpack 4, or know where's there's any info that could help.  To be honest, it wouldn't be the end of the world if I had to roll back to 3.x, but worth asking.

Cheers
Chris

**Comment by zackljackson** [comment]
PR will be released soon. In the meantime. 

Client build:

``` optimization: {
        minimizer: [
            new UglifyJSPlugin({
                uglifyOptions: {
                    output: {
                        comments: false,
                        ascii_only: true
                    },
                    compress: {
                        comparisons: false
                    }
                }
            })
        ],
        runtimeChunk: {
            name: 'bootstrap'
        },
        splitChunks: {
            chunks: 'initial', // <-- The key to this
            cacheGroups: {
                vendors: {
                    test: /[\\/]node_modules[\\/]/,
                    name: 'vendor'
                }
            }
        }
    }```

SERVER
```    new webpack.optimize.LimitChunkCountPlugin({
        maxChunks: 1
    })```

**Comment by sudarshang** [comment]
@zackljackson this is really cool. As far as I can tell the version 3 of react-universal-component and babel-plugin-universal-import have not been released. Can I install the `master` versions of these two components to test this PR?

**Comment by zackljackson** [comment]
Not just yet, I’m in the middle of moving apartments which delayed my a tiny bit. There’s going to be an update any day that’ll get you up and running. Worst case. You should be able to use the webpack 4 branch of the universal plugin (on zackljackson not faceyspacey ) 

This relies on that mini-css-extract plugin. 

I however got word that someone updated our own extract css chunks plugin, so I am looking at testing and merging their solution to keep it all in the ecosystem. 

It depends on the urgency, but if you can, give me a day or two and I’ll have a branch you can test with a PR up

**Comment by zackljackson** [comment]
This isn’t production ready... so just be cautions till we can verify the integrity of the solution

**Comment by sudarshang** [comment]
I am upgrading react-static to [webpack-4](https://github.com/nozzle/react-static/pull/605).  I was trying to figure out how to upgrade the universal ecosystem to webpack 4 so I am more than happy to find that you have already done all the work. I am happy to test your code in the react-static library. Please update this issue when you think I should start testing. 

Does the universal ecosystem plan to support both the mini-css-extract plugin and the extract-css-chunks plugin going forward?

**Comment by zackljackson** [comment]
The plan is to provide a good experience for our developers ☺️ While also planning out better things that will greatly improve Frontend development the same way that our universal system did. Mini css extract works but it’s not as smooth as ours I have discovered. It is also a very new plugin. 

Mini-css-chunks doesn’t play as nicely as ours from my initial tests. It requires manually flipping between style-loader and mini-css-extract. It’s not as seamless as ours which is built to hot reload internally. 

In an ideal world, it would be nice to support both and I believe you can actually use mini css extract with our existing code. But the import css might throw a few complaints saying it cannot find chunks. Just because it’s technically not managing them anymore. Mini css extract is. 

It could be on the roadmap if need be, but I’d hold off on introducing more complexity and variables to universal which itself is already an intricate setup. At least for the initial Webpack 4 support announcement & release. 

I would first want to update the readMe start using GitHub wikis, otherwise you’ve got notes on webpack 3 and 4 plus css chunking in both mini css and extract css chunks, and how universal actually works.

**Comment by zackljackson** [comment]
Update for you ❤️

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/60#issuecomment-392317314

**Comment by zackljackson** [comment]
PR now open

**Comment by zackljackson** [comment]
Merged!

**Comment by zackljackson** [comment]
Aggressive and more complex chunk splitting now supported
https://github.com/faceyspacey/webpack-flush-chunks/pull/59

Now available via `@next` tag on NPM
